#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AG_RecentlyShot

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AG_RecentlyShot.AG_RecentlyShot_C
// 0x0008 (0x0030 - 0x0028)
class UAG_RecentlyShot_C final : public UAIActionGate
{
public:
	double                                        TimeSince;                                         // 0x0028(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	bool CanOpen(const struct FAIActionDecisionContext& Context) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AG_RecentlyShot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AG_RecentlyShot_C")
	}
	static class UAG_RecentlyShot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAG_RecentlyShot_C>();
	}
};
DUMPER7_ASSERTS_UAG_RecentlyShot_C;

}

