#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ANIMBP_AKM

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function ANIMBP_AKM.ANIMBP_AKM_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct ANIMBP_AKM_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ANIMBP_AKM_C_AnimGraph;

// Function ANIMBP_AKM.ANIMBP_AKM_C.ExecuteUbergraph_ANIMBP_AKM
// 0x0004 (0x0004 - 0x0000)
struct ANIMBP_AKM_C_ExecuteUbergraph_ANIMBP_AKM final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ANIMBP_AKM_C_ExecuteUbergraph_ANIMBP_AKM;

}

