#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ClueFlare

#include "Basic.hpp"

#include "BP_ClueFlare_classes.hpp"
#include "BP_ClueFlare_parameters.hpp"


namespace SDK
{

// Function BP_ClueFlare.BP_ClueFlare_C.ExecuteUbergraph_BP_ClueFlare
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ClueFlare_C::ExecuteUbergraph_BP_ClueFlare(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClueFlare_C", "ExecuteUbergraph_BP_ClueFlare");

	Params::BP_ClueFlare_C_ExecuteUbergraph_BP_ClueFlare Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ClueFlare.BP_ClueFlare_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ClueFlare_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClueFlare_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ClueFlare.BP_ClueFlare_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_ClueFlare_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClueFlare_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ClueFlare.BP_ClueFlare_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_ClueFlare_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClueFlare_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

