#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Clock_001

#include "Basic.hpp"

#include "BP_Clock_001_classes.hpp"
#include "BP_Clock_001_parameters.hpp"


namespace SDK
{

// Function BP_Clock_001.BP_Clock_001_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Clock_001_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Clock_001_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Clock_001.BP_Clock_001_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Clock_001_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Clock_001_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Clock_001.BP_Clock_001_C.ExecuteUbergraph_BP_Clock_001
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Clock_001_C::ExecuteUbergraph_BP_Clock_001(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Clock_001_C", "ExecuteUbergraph_BP_Clock_001");

	Params::BP_Clock_001_C_ExecuteUbergraph_BP_Clock_001 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

