#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Destruction_Can_01

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Destruction_Can_01.BP_Destruction_Can_01_C
// 0x0018 (0x02F0 - 0x02D8)
class ABP_Destruction_Can_01_C final : public ADynamicWorldItem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFMODAudioComponent*                    FMOD_CanHit;                                       // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         HitLimit;                                          // 0x02E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReEnable_Hit();
	void ReceiveHit(class UPrimitiveComponent* MyComp, class AActor* Other, class UPrimitiveComponent* OtherComp, bool bSelfMoved, const struct FVector& HitLocation, const struct FVector& HitNormal, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	void ExecuteUbergraph_BP_Destruction_Can_01(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Destruction_Can_01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Destruction_Can_01_C")
	}
	static class ABP_Destruction_Can_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Destruction_Can_01_C>();
	}
};
DUMPER7_ASSERTS_ABP_Destruction_Can_01_C;

}

