#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RoNBloodPool

#include "Basic.hpp"

#include "BP_RoNBloodPool_classes.hpp"
#include "BP_RoNBloodPool_parameters.hpp"


namespace SDK
{

// Function BP_RoNBloodPool.BP_RoNBloodPool_C.ExecuteUbergraph_BP_RoNBloodPool
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RoNBloodPool_C::ExecuteUbergraph_BP_RoNBloodPool(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RoNBloodPool_C", "ExecuteUbergraph_BP_RoNBloodPool");

	Params::BP_RoNBloodPool_C_ExecuteUbergraph_BP_RoNBloodPool Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RoNBloodPool.BP_RoNBloodPool_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_RoNBloodPool_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RoNBloodPool_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RoNBloodPool.BP_RoNBloodPool_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RoNBloodPool_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RoNBloodPool_C", "ReceiveTick");

	Params::BP_RoNBloodPool_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

