#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DefaultHoveredTextStyle

#include "Basic.hpp"

#include "DefaultNormalTextStyle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DefaultHoveredTextStyle.DefaultHoveredTextStyle_C
// 0x0000 (0x01B0 - 0x01B0)
class UDefaultHoveredTextStyle_C final : public UDefaultNormalTextStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DefaultHoveredTextStyle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DefaultHoveredTextStyle_C")
	}
	static class UDefaultHoveredTextStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDefaultHoveredTextStyle_C>();
	}
};
DUMPER7_ASSERTS_UDefaultHoveredTextStyle_C;

}

