#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_CarColors

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_CarColors.E_CarColors
// NumValues: 0x0011
enum class E_CarColors : uint8
{
	NewEnumerator6                           = 0,
	NewEnumerator10                          = 1,
	NewEnumerator14                          = 2,
	NewEnumerator3                           = 3,
	NewEnumerator9                           = 4,
	NewEnumerator2                           = 5,
	NewEnumerator15                          = 6,
	NewEnumerator0                           = 7,
	NewEnumerator13                          = 8,
	NewEnumerator4                           = 9,
	NewEnumerator5                           = 10,
	NewEnumerator8                           = 11,
	NewEnumerator12                          = 12,
	NewEnumerator7                           = 13,
	NewEnumerator1                           = 14,
	NewEnumerator11                          = 15,
	E_MAX                                    = 16,
};

}

