#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_LicesPlate_Types

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_LicesPlate_Types.E_LicesPlate_Types
// NumValues: 0x0006
enum class E_LicesPlate_Types : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	E_LicesPlate_MAX                         = 5,
};

}

