#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GM_Incrimination

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GM_Incrimination.GM_Incrimination_C
// 0x0010 (0x0A50 - 0x0A40)
class AGM_Incrimination_C final : public AIncriminationGM
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0A40(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GM_Incrimination_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GM_Incrimination_C")
	}
	static class AGM_Incrimination_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGM_Incrimination_C>();
	}
};
DUMPER7_ASSERTS_AGM_Incrimination_C;

}

