#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GS_TDM

#include "Basic.hpp"


namespace SDK::Params
{

// Function GS_TDM.GS_TDM_C.ExecuteUbergraph_GS_TDM
// 0x0010 (0x0010 - 0x0000)
struct GS_TDM_C_ExecuteUbergraph_GS_TDM final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GS_TDM_C_ExecuteUbergraph_GS_TDM;

}

