#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InviteButtonStyle1

#include "Basic.hpp"

#include "BaseButtonStyle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass InviteButtonStyle1.InviteButtonStyle1_C
// 0x0000 (0x07E0 - 0x07E0)
class UInviteButtonStyle1_C final : public UBaseButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("InviteButtonStyle1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InviteButtonStyle1_C")
	}
	static class UInviteButtonStyle1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInviteButtonStyle1_C>();
	}
};
DUMPER7_ASSERTS_UInviteButtonStyle1_C;

}

