#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoadoutSlotButtonStyle_Gamepad

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LoadoutSlotButtonStyle_Gamepad.LoadoutSlotButtonStyle_Gamepad_C
// 0x0000 (0x07C0 - 0x07C0)
class ULoadoutSlotButtonStyle_Gamepad_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LoadoutSlotButtonStyle_Gamepad_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LoadoutSlotButtonStyle_Gamepad_C")
	}
	static class ULoadoutSlotButtonStyle_Gamepad_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULoadoutSlotButtonStyle_Gamepad_C>();
	}
};
DUMPER7_ASSERTS_ULoadoutSlotButtonStyle_Gamepad_C;

}

