#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Melee_Knife

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Melee_Knife.Melee_Knife_C
// 0x0000 (0x13A0 - 0x13A0)
class AMelee_Knife_C final : public AMeleeWeapon
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Melee_Knife_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Melee_Knife_C")
	}
	static class AMelee_Knife_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMelee_Knife_C>();
	}
};
DUMPER7_ASSERTS_AMelee_Knife_C;

}

