#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Modio

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// Enum Modio.EModioModfilePlatform
// NumValues: 0x000D
enum class EModioModfilePlatform : uint8
{
	Windows                                  = 0,
	Mac                                      = 1,
	Linux                                    = 2,
	Android                                  = 3,
	iOS                                      = 4,
	XboxOne                                  = 5,
	XboxSeriesX                              = 6,
	PS4                                      = 7,
	PS5                                      = 8,
	Switch                                   = 9,
	Oculus                                   = 10,
	Source                                   = 11,
	EModioModfilePlatform_MAX                = 12,
};

// Enum Modio.EGameMaturityFlags
// NumValues: 0x0004
enum class EGameMaturityFlags : uint8
{
	None                                     = 0,
	MatureModsAllowed                        = 1,
	MatureAudiencesOnly                      = 2,
	EGameMaturityFlags_MAX                   = 3,
};

// Enum Modio.EGameMonetizationFlags
// NumValues: 0x0005
enum class EGameMonetizationFlags : uint8
{
	None                                     = 0,
	Monetization                             = 1,
	Marketplace                              = 2,
	PartnerProgram                           = 4,
	EGameMonetizationFlags_MAX               = 5,
};

// Enum Modio.EModioModServerSideStatus
// NumValues: 0x0004
enum class EModioModServerSideStatus : uint8
{
	NotAccepted                              = 0,
	Accepted                                 = 1,
	Deleted                                  = 3,
	EModioModServerSideStatus_MAX            = 4,
};

// Enum Modio.EModioVirusStatus
// NumValues: 0x0003
enum class EModioVirusStatus : uint8
{
	NoThreat                                 = 0,
	Malicious                                = 1,
	EModioVirusStatus_MAX                    = 2,
};

// Enum Modio.EModioVirusScanStatus
// NumValues: 0x0007
enum class EModioVirusScanStatus : uint8
{
	NotScanned                               = 0,
	ScanComplete                             = 1,
	InProgress                               = 2,
	TooLargeToScan                           = 3,
	FileNotFound                             = 4,
	ErrorScanning                            = 5,
	EModioVirusScanStatus_MAX                = 6,
};

// Enum Modio.EModioObjectVisibilityFlags
// NumValues: 0x0003
enum class EModioObjectVisibilityFlags : uint8
{
	Hidden                                   = 0,
	Public                                   = 1,
	EModioObjectVisibilityFlags_MAX          = 2,
};

// Enum Modio.EModioMaturityFlags
// NumValues: 0x0006
enum class EModioMaturityFlags : uint8
{
	None                                     = 0,
	Alcohol                                  = 1,
	Drugs                                    = 2,
	Violence                                 = 4,
	Explicit                                 = 8,
	EModioMaturityFlags_MAX                  = 9,
};

// Enum Modio.EModioModManagementEventType
// NumValues: 0x0009
enum class EModioModManagementEventType : uint8
{
	Installed                                = 0,
	Uninstalled                              = 1,
	Updated                                  = 2,
	Uploaded                                 = 3,
	BeginInstall                             = 4,
	BeginUninstall                           = 5,
	BeginUpdate                              = 6,
	BeginUpload                              = 7,
	EModioModManagementEventType_MAX         = 8,
};

// Enum Modio.EModioAuthenticationProvider
// NumValues: 0x000D
enum class EModioAuthenticationProvider : uint8
{
	XboxLive                                 = 0,
	Steam                                    = 1,
	GoG                                      = 2,
	Itch                                     = 3,
	Switch                                   = 4,
	Discord                                  = 5,
	PSN                                      = 6,
	Epic                                     = 7,
	Oculus                                   = 8,
	OpenID                                   = 9,
	GoogleIDToken                            = 10,
	GoogleServerSideToken                    = 11,
	EModioAuthenticationProvider_MAX         = 12,
};

// Enum Modio.EModioEnvironment
// NumValues: 0x0003
enum class EModioEnvironment : uint8
{
	Test                                     = 0,
	Live                                     = 1,
	EModioEnvironment_MAX                    = 2,
};

// Enum Modio.EModioPortal
// NumValues: 0x000B
enum class EModioPortal : uint8
{
	None                                     = 0,
	Apple                                    = 1,
	EpicGamesStore                           = 2,
	GOG                                      = 3,
	Google                                   = 4,
	Itchio                                   = 5,
	Nintendo                                 = 6,
	PSN                                      = 7,
	Steam                                    = 8,
	XboxLive                                 = 9,
	EModioPortal_MAX                         = 10,
};

// Enum Modio.EModioPlatformName
// NumValues: 0x000C
enum class EModioPlatformName : uint8
{
	Windows                                  = 0,
	Mac                                      = 1,
	Linux                                    = 2,
	PS4                                      = 3,
	PS5                                      = 4,
	XBoxOne                                  = 5,
	XSX                                      = 6,
	Switch                                   = 7,
	Unknown                                  = 8,
	Android                                  = 9,
	iOS                                      = 10,
	EModioPlatformName_MAX                   = 11,
};

// Enum Modio.EModioLogoSize
// NumValues: 0x0005
enum class EModioLogoSize : uint8
{
	Thumb320                                 = 0,
	Thumb640                                 = 1,
	Thumb1280                                = 2,
	Original                                 = 3,
	EModioLogoSize_MAX                       = 4,
};

// Enum Modio.EModioAvatarSize
// NumValues: 0x0004
enum class EModioAvatarSize : uint8
{
	Original                                 = 0,
	Thumb50                                  = 1,
	Thumb100                                 = 2,
	EModioAvatarSize_MAX                     = 3,
};

// Enum Modio.EModioGallerySize
// NumValues: 0x0004
enum class EModioGallerySize : uint8
{
	Original                                 = 0,
	Thumb320                                 = 1,
	Thumb1280                                = 2,
	EModioGallerySize_MAX                    = 3,
};

// Enum Modio.EModioLogLevel
// NumValues: 0x0006
enum class EModioLogLevel : uint8
{
	Trace                                    = 0,
	Detailed                                 = 1,
	Info                                     = 2,
	Warning                                  = 3,
	Error                                    = 4,
	EModioLogLevel_MAX                       = 5,
};

// Enum Modio.EModioLanguage
// NumValues: 0x0014
enum class EModioLanguage : uint8
{
	English                                  = 0,
	Bulgarian                                = 1,
	French                                   = 2,
	German                                   = 3,
	Italian                                  = 4,
	Polish                                   = 5,
	Portuguese                               = 6,
	Hungarian                                = 7,
	Japanese                                 = 8,
	Korean                                   = 9,
	Russian                                  = 10,
	Spanish                                  = 11,
	Thai                                     = 12,
	ChineseSimplified                        = 13,
	ChineseTraditional                       = 14,
	Turkish                                  = 15,
	Ukrainian                                = 16,
	Arabic                                   = 17,
	Count                                    = 18,
	EModioLanguage_MAX                       = 19,
};

// Enum Modio.EModioModChangeType
// NumValues: 0x0004
enum class EModioModChangeType : uint8
{
	Added                                    = 0,
	Removed                                  = 1,
	Updated                                  = 2,
	EModioModChangeType_MAX                  = 3,
};

// Enum Modio.EFileSizeUnit
// NumValues: 0x0006
enum class EFileSizeUnit : uint8
{
	Largest                                  = 0,
	B                                        = 1,
	KB                                       = 1024,
	MB                                       = 1048576,
	GB                                       = 1073741824,
	EFileSizeUnit_MAX                        = 1073741825,
};

// Enum Modio.EModioEntitlementConsumptionState
// NumValues: 0x0005
enum class EModioEntitlementConsumptionState : uint8
{
	Failed                                   = 0,
	Pending                                  = 1,
	Fulfilled                                = 2,
	ConsumeLimitExceeded                     = 3,
	EModioEntitlementConsumptionState_MAX    = 4,
};

// Enum Modio.EModioEntitlementType
// NumValues: 0x0002
enum class EModioEntitlementType : uint8
{
	VirtualCurrency                          = 0,
	EModioEntitlementType_MAX                = 1,
};

// Enum Modio.EModioErrorCondition
// NumValues: 0x0028
enum class EModioErrorCondition : uint8
{
	NoError                                  = 0,
	NetworkError                             = 2,
	ConfigurationError                       = 3,
	InvalidArgsError                         = 4,
	FilesystemError                          = 5,
	InternalError                            = 6,
	ApiErrorRefSuccess                       = 7,
	EntityNotFoundError                      = 12,
	UserTermsOfUseError                      = 13,
	SubmitReportError                        = 14,
	UserNotAuthenticatedError                = 15,
	SDKNotInitialized                        = 16,
	UserAlreadyAuthenticatedError            = 17,
	SystemError                              = 18,
	OperationCanceled                        = 19,
	ModManagementDisabled                    = 20,
	RateLimited                              = 21,
	ModBeingProcessed                        = 22,
	InsufficientSpace                        = 23,
	SDKAlreadyInitialized                    = 24,
	ModManagementAlreadyEnabled              = 25,
	InsufficientPermissions                  = 26,
	EmailLoginCodeInvalid                    = 27,
	AlreadySubscribed                        = 28,
	InstallOrUpdateCancelled                 = 29,
	UploadCancelled                          = 30,
	TempModSetNotInitialized                 = 31,
	MonetizationOperationError               = 32,
	PaymentTransactionFailed                 = 33,
	IncorrectPrice                           = 34,
	ItemAlreadyOwned                         = 35,
	ParentalControlRestrictions              = 36,
	MetricsSessionNotInitialized             = 37,
	MetricsSessionAlreadyInitialized         = 38,
	MetricsSessionIsActive                   = 39,
	MetricsSessionIsNotActive                = 40,
	MetricsSessionHasNoMods                  = 41,
	PremiumFeatureNotAvailable               = 42,
	EmailExchangeCodeAlreadyRedeemed         = 43,
	EModioErrorCondition_MAX                 = 44,
};

// Enum Modio.EModioSortFieldType
// NumValues: 0x0009
enum class EModioSortFieldType : uint8
{
	ID                                       = 0,
	DownloadsToday                           = 1,
	SubscriberCount                          = 2,
	Rating                                   = 3,
	DateMarkedLive                           = 4,
	DateUpdated                              = 5,
	DownloadsTotal                           = 6,
	Alphabetical                             = 7,
	EModioSortFieldType_MAX                  = 8,
};

// Enum Modio.EModioSortDirection
// NumValues: 0x0003
enum class EModioSortDirection : uint8
{
	Ascending                                = 0,
	Descending                               = 1,
	EModioSortDirection_MAX                  = 2,
};

// Enum Modio.EModioRevenueFilterType
// NumValues: 0x0004
enum class EModioRevenueFilterType : uint8
{
	Free                                     = 0,
	Paid                                     = 1,
	FreeAndPaid                              = 2,
	EModioRevenueFilterType_MAX              = 3,
};

// Enum Modio.EModioImageState
// NumValues: 0x0005
enum class EModioImageState : uint8
{
	OnDisc                                   = 0,
	LoadingIntoMemory                        = 1,
	InMemory                                 = 2,
	Corrupted                                = 3,
	EModioImageState_MAX                     = 4,
};

// Enum Modio.EModioModState
// NumValues: 0x0007
enum class EModioModState : uint8
{
	InstallationPending                      = 0,
	Installed                                = 1,
	UpdatePending                            = 2,
	Downloading                              = 3,
	Extracting                               = 4,
	UninstallPending                         = 5,
	EModioModState_MAX                       = 6,
};

// Enum Modio.EModioModProgressState
// NumValues: 0x0006
enum class EModioModProgressState : uint8
{
	Initializing                             = 0,
	Downloading                              = 1,
	Extracting                               = 2,
	Compressing                              = 3,
	Uploading                                = 4,
	EModioModProgressState_MAX               = 5,
};

// Enum Modio.EModioOpenStoreResult
// NumValues: 0x0005
enum class EModioOpenStoreResult : uint8
{
	Success                                  = 0,
	FailedInactive                           = 1,
	FailedUnsupportedPlatform                = 2,
	FailedUnknown                            = 3,
	EModioOpenStoreResult_MAX                = 4,
};

// Enum Modio.EModioRating
// NumValues: 0x0004
enum class EModioRating : uint8
{
	Neutral                                  = 0,
	Positive                                 = 1,
	Negative                                 = 2,
	EModioRating_MAX                         = 3,
};

// Enum Modio.EModioReportType
// NumValues: 0x0009
enum class EModioReportType : uint8
{
	Generic                                  = 0,
	DMCA                                     = 1,
	NotWorking                               = 2,
	RudeContent                              = 3,
	IllegalContent                           = 4,
	StolenContent                            = 5,
	FalseInformation                         = 6,
	Other                                    = 7,
	EModioReportType_MAX                     = 8,
};

// ScriptStruct Modio.ModioPagedResult
// 0x0014 (0x0014 - 0x0000)
struct FModioPagedResult final
{
public:
	int32                                         PageIndex;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         PageSize;                                          // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         PageCount;                                         // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         TotalResultCount;                                  // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         ResultCount;                                       // 0x0010(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
};
DUMPER7_ASSERTS_FModioPagedResult;

// ScriptStruct Modio.ModioEntitlementConsumptionVirtualCurrencyDetails
// 0x0004 (0x0004 - 0x0000)
struct FModioEntitlementConsumptionVirtualCurrencyDetails final
{
public:
	int32                                         TokensAllocated;                                   // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioEntitlementConsumptionVirtualCurrencyDetails;

// ScriptStruct Modio.EntitlementConsumptionStatus
// 0x0030 (0x0030 - 0x0000)
struct FEntitlementConsumptionStatus final
{
public:
	class FString                                 TransactionId;                                     // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EModioEntitlementConsumptionState             TransactionState;                                  // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 SkuId;                                             // 0x0018(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          EntitlementConsumed;                               // 0x0028(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EModioEntitlementType                         EntitlementType;                                   // 0x0029(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2A[0x2];                                       // 0x002A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FModioEntitlementConsumptionVirtualCurrencyDetails VirtualCurrencyDetails;                // 0x002C(0x0004)(BlueprintVisible, BlueprintReadOnly, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FEntitlementConsumptionStatus;

// ScriptStruct Modio.ModioOptionalEntitlementWalletBalance
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FModioOptionalEntitlementWalletBalance final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalEntitlementWalletBalance;

// ScriptStruct Modio.ModioEntitlementConsumptionStatusList
// 0x0038 (0x0038 - 0x0000)
struct FModioEntitlementConsumptionStatusList final
{
public:
	struct FModioPagedResult                      PagedResult;                                       // 0x0000(0x0014)(BlueprintVisible, BlueprintReadOnly, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FEntitlementConsumptionStatus>  InternalList;                                      // 0x0018(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	struct FModioOptionalEntitlementWalletBalance WalletBalance;                                     // 0x0028(0x0010)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioEntitlementConsumptionStatusList;

// ScriptStruct Modio.ModioGameID
// 0x0008 (0x0008 - 0x0000)
struct FModioGameID final
{
public:
	int64                                         GameId;                                            // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};
DUMPER7_ASSERTS_FModioGameID;

// ScriptStruct Modio.ModioLogo
// 0x0050 (0x0050 - 0x0000)
struct FModioLogo final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Original;                                          // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Thumb320x180;                                      // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Thumb640x360;                                      // 0x0030(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Thumb1280x720;                                     // 0x0040(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioLogo;

// ScriptStruct Modio.ModioIcon
// 0x0050 (0x0050 - 0x0000)
struct FModioIcon final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Original;                                          // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Thumb64x64;                                        // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Thumb128x128;                                      // 0x0030(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Thumb256x256;                                      // 0x0040(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioIcon;

// ScriptStruct Modio.ModioGamePlatform
// 0x0003 (0x0003 - 0x0000)
struct FModioGamePlatform final
{
public:
	EModioModfilePlatform                         Platform;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Locked;                                            // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Moderated;                                         // 0x0002(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioGamePlatform;

// ScriptStruct Modio.ModioHeaderImage
// 0x0020 (0x0020 - 0x0000)
struct FModioHeaderImage final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Original;                                          // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioHeaderImage;

// ScriptStruct Modio.ModioTheme
// 0x0060 (0x0060 - 0x0000)
struct FModioTheme final
{
public:
	class FString                                 Primary;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Dark;                                              // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Light;                                             // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Success;                                           // 0x0030(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Warning;                                           // 0x0040(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Danger;                                            // 0x0050(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioTheme;

// ScriptStruct Modio.ModioGameStats
// 0x0038 (0x0038 - 0x0000)
struct FModioGameStats final
{
public:
	struct FModioGameID                           GameId;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ModCountTotal;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ModDownloadsToday;                                 // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ModDownloadsTotal;                                 // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ModDownloadsDailyAverage;                          // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ModSubscribersTotal;                               // 0x0028(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         DateExpires;                                       // 0x0030(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioGameStats;

// ScriptStruct Modio.ModioOtherUrl
// 0x0020 (0x0020 - 0x0000)
struct FModioOtherUrl final
{
public:
	class FString                                 Label;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 URL;                                               // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioOtherUrl;

// ScriptStruct Modio.ModioModTagLocalizationData
// 0x0060 (0x0060 - 0x0000)
struct FModioModTagLocalizationData final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FString, class FText>              Translations;                                      // 0x0010(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnTemplate, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioModTagLocalizationData;

// ScriptStruct Modio.ModioLocalizedTagCategory
// 0x0020 (0x0020 - 0x0000)
struct FModioLocalizedTagCategory final
{
public:
	class FString                                 GroupName;                                         // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         Tags;                                              // 0x0010(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioLocalizedTagCategory;

// ScriptStruct Modio.ModioModTagInfo
// 0x00B8 (0x00B8 - 0x0000)
struct FModioModTagInfo final
{
public:
	class FString                                 TagGroupName;                                      // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         TagGroupValues;                                    // 0x0010(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, NativeAccessSpecifierPublic)
	TMap<class FString, class FText>              TagGroupNameLocalizationData;                      // 0x0020(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnTemplate, NativeAccessSpecifierPublic)
	TArray<struct FModioModTagLocalizationData>   TagGroupValueLocalizationData;                     // 0x0070(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, NativeAccessSpecifierPublic)
	bool                                          bAllowMultipleSelection;                           // 0x0080(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHidden;                                           // 0x0081(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLocked;                                           // 0x0082(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_83[0x5];                                       // 0x0083(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Locale;                                            // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FModioLocalizedTagCategory             LocalizedTagCategoryDataCurrentLocale;             // 0x0098(0x0020)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnTemplate, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioModTagInfo;

// ScriptStruct Modio.ModioGameInfo
// 0x0230 (0x0230 - 0x0000)
struct FModioGameInfo final
{
public:
	struct FModioGameID                           GameId;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              DateAdded;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              DateUpdated;                                       // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              DateLive;                                          // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 UgcName;                                           // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FModioIcon                             Icon;                                              // 0x0030(0x0050)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FModioLogo                             Logo;                                              // 0x0080(0x0050)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FModioHeaderImage                      HeaderImage;                                       // 0x00D0(0x0020)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	class FString                                 Name;                                              // 0x00F0(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Summary;                                           // 0x0100(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Instructions;                                      // 0x0110(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 InstructionsUrl;                                   // 0x0120(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProfileUrl;                                        // 0x0130(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FModioTheme                            Theme;                                             // 0x0140(0x0060)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FModioGameStats                        Stats;                                             // 0x01A0(0x0038)(BlueprintVisible, BlueprintReadOnly, NoDestructor, NativeAccessSpecifierPublic)
	TArray<struct FModioOtherUrl>                 OtherUrls;                                         // 0x01D8(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<EModioModfilePlatform>                 Platforms;                                         // 0x01E8(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          bAllowNegativeRatings;                             // 0x01F8(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGameMonetizationFlags                        GameMonetizationOptions;                           // 0x01F9(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGameMaturityFlags                            GameMaturityOptions;                               // 0x01FA(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1FB[0x5];                                      // 0x01FB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 VirtualTokenName;                                  // 0x0200(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FModioGamePlatform>             PlatformSupport;                                   // 0x0210(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FModioModTagInfo>               TagOptions;                                        // 0x0220(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioGameInfo;

// ScriptStruct Modio.ModioGameInfoList
// 0x0028 (0x0028 - 0x0000)
struct FModioGameInfoList final
{
public:
	struct FModioPagedResult                      PagedResult;                                       // 0x0000(0x0014)(NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FModioGameInfo>                 InternalList;                                      // 0x0018(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioGameInfoList;

// ScriptStruct Modio.ModioOptionalEntitlementConsumptionStatusList
// 0x0040 (0x0040 - 0x0000)
struct alignas(0x08) FModioOptionalEntitlementConsumptionStatusList final
{
public:
	uint8                                         Pad_0[0x40];                                       // 0x0000(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalEntitlementConsumptionStatusList;

// ScriptStruct Modio.ModioApiKey
// 0x0010 (0x0010 - 0x0000)
struct FModioApiKey final
{
public:
	class FString                                 ApiKey;                                            // 0x0000(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};
DUMPER7_ASSERTS_FModioApiKey;

// ScriptStruct Modio.ModioGuid
// 0x0010 (0x0010 - 0x0000)
struct FModioGuid final
{
public:
	class FString                                 InternalGuid;                                      // 0x0000(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};
DUMPER7_ASSERTS_FModioGuid;

// ScriptStruct Modio.ModioOptionalUserList
// 0x0030 (0x0030 - 0x0000)
struct alignas(0x08) FModioOptionalUserList final
{
public:
	uint8                                         Pad_0[0x30];                                       // 0x0000(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalUserList;

// ScriptStruct Modio.ModioOptionalGuid
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FModioOptionalGuid final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalGuid;

// ScriptStruct Modio.ModioOptionalModChangeMap
// 0x0058 (0x0058 - 0x0000)
struct alignas(0x08) FModioOptionalModChangeMap final
{
public:
	uint8                                         Pad_0[0x58];                                       // 0x0000(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalModChangeMap;

// ScriptStruct Modio.ModioOptionalModID
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FModioOptionalModID final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalModID;

// ScriptStruct Modio.ModioUnsigned64
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FModioUnsigned64 final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioUnsigned64;

// ScriptStruct Modio.ModioEntitlementWalletBalance
// 0x0008 (0x0008 - 0x0000)
struct FModioEntitlementWalletBalance final
{
public:
	struct FModioUnsigned64                       Balance;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioEntitlementWalletBalance;

// ScriptStruct Modio.ModioModStats
// 0x0058 (0x0058 - 0x0000)
struct FModioModStats final
{
public:
	int64                                         PopularityRankPosition;                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         PopularityRankTotalMods;                           // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         DownloadsTotal;                                    // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         SubscribersTotal;                                  // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         RatingTotal;                                       // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         RatingPositive;                                    // 0x0028(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         RatingNegative;                                    // 0x0030(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         RatingPercentagePositive;                          // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RatingWeightedAggregate;                           // 0x0040(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 RatingDisplayText;                                 // 0x0048(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioModStats;

// ScriptStruct Modio.ModioModID
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FModioModID final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioModID;

// ScriptStruct Modio.ModioUserID
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FModioUserID final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioUserID;

// ScriptStruct Modio.ModioUser
// 0x0040 (0x0040 - 0x0000)
struct FModioUser final
{
public:
	struct FModioUserID                           UserId;                                            // 0x0000(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Username;                                          // 0x0008(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              DateOnline;                                        // 0x0018(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProfileUrl;                                        // 0x0020(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DisplayNamePortal;                                 // 0x0030(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioUser;

// ScriptStruct Modio.ModioMetadata
// 0x0020 (0x0020 - 0x0000)
struct FModioMetadata final
{
public:
	class FString                                 Key;                                               // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Value;                                             // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioMetadata;

// ScriptStruct Modio.ModioModTag
// 0x0028 (0x0028 - 0x0000)
struct FModioModTag final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FText                                   TagLocalized;                                      // 0x0010(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnTemplate, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioModTag;

// ScriptStruct Modio.ModioFileMetadataID
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FModioFileMetadataID final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioFileMetadataID;

// ScriptStruct Modio.ModioFileMetadata
// 0x0070 (0x0070 - 0x0000)
struct FModioFileMetadata final
{
public:
	struct FModioFileMetadataID                   MetadataId;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FModioModID                            ModId;                                             // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              DateAdded;                                         // 0x0010(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EModioVirusScanStatus                         CurrentVirusScanStatus;                            // 0x0018(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EModioVirusStatus                             CurrentVirusStatus;                                // 0x0019(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A[0x6];                                       // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         Filesize;                                          // 0x0020(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         FilesizeUncompressed;                              // 0x0028(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Filename;                                          // 0x0030(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Version;                                           // 0x0040(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Changelog;                                         // 0x0050(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 MetadataBlob;                                      // 0x0060(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioFileMetadata;

// ScriptStruct Modio.ModioYoutubeURLList
// 0x0001 (0x0001 - 0x0000)
struct FModioYoutubeURLList final
{
public:
	uint8                                         Pad_0[0x1];                                        // 0x0000(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioYoutubeURLList;

// ScriptStruct Modio.ModioSketchfabURLList
// 0x0001 (0x0001 - 0x0000)
struct FModioSketchfabURLList final
{
public:
	uint8                                         Pad_0[0x1];                                        // 0x0000(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioSketchfabURLList;

// ScriptStruct Modio.ModioModInfo
// 0x01E8 (0x01E8 - 0x0000)
struct FModioModInfo final
{
public:
	struct FModioModID                            ModId;                                             // 0x0000(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProfileName;                                       // 0x0008(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProfileSummary;                                    // 0x0018(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProfileDescription;                                // 0x0028(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProfileDescriptionPlaintext;                       // 0x0038(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProfileUrl;                                        // 0x0048(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FModioUser                             ProfileSubmittedBy;                                // 0x0058(0x0040)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnTemplate, NativeAccessSpecifierPublic)
	struct FDateTime                              ProfileDateAdded;                                  // 0x0098(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              ProfileDateUpdated;                                // 0x00A0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              ProfileDateLive;                                   // 0x00A8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EModioMaturityFlags                           ProfileMaturityOption;                             // 0x00B0(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bVisible;                                          // 0x00B1(0x0001)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EModioObjectVisibilityFlags                   Visibility;                                        // 0x00B2(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Dependencies;                                      // 0x00B3(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 MetadataBlob;                                      // 0x00B8(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FModioFileMetadata                     FileInfo;                                          // 0x00C8(0x0070)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnTemplate, NativeAccessSpecifierPublic)
	TArray<struct FModioMetadata>                 MetadataKvp;                                       // 0x0138(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, NativeAccessSpecifierPublic)
	TArray<struct FModioModTag>                   Tags;                                              // 0x0148(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, NativeAccessSpecifierPublic)
	int32                                         NumGalleryImages;                                  // 0x0158(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FModioYoutubeURLList                   YoutubeURLs;                                       // 0x0160(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_161[0xF];                                      // 0x0161(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FModioSketchfabURLList                 SketchfabURLs;                                     // 0x0170(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_171[0xF];                                      // 0x0171(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FModioModStats                         Stats;                                             // 0x0180(0x0058)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnTemplate, NativeAccessSpecifierPublic)
	EModioModServerSideStatus                     ModStatus;                                         // 0x01D8(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D9[0x7];                                      // 0x01D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FModioUnsigned64                       Price;                                             // 0x01E0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnTemplate, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioModInfo;

// ScriptStruct Modio.ModioModInfoList
// 0x0028 (0x0028 - 0x0000)
struct FModioModInfoList final
{
public:
	struct FModioPagedResult                      PagedResult;                                       // 0x0000(0x0014)(NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FModioModInfo>                  InternalList;                                      // 0x0018(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioModInfoList;

// ScriptStruct Modio.ModioFilterParams
// 0x00B8 (0x00B8 - 0x0000)
struct alignas(0x08) FModioFilterParams final
{
public:
	uint8                                         Pad_0[0xB8];                                       // 0x0000(0x00B8)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioFilterParams;

// ScriptStruct Modio.ModioPresetFilterParams
// 0x0048 (0x0048 - 0x0000)
struct FModioPresetFilterParams final
{
public:
	class FText                                   PresetName;                                        // 0x0000(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<class FString>                         Tags;                                              // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<class FString>                         ExcludedTags;                                      // 0x0028(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	EModioSortDirection                           Direction;                                         // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EModioSortFieldType                           SortField;                                         // 0x0039(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3A[0x6];                                       // 0x003A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         Count;                                             // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioPresetFilterParams;

// ScriptStruct Modio.ModioImageWrapper
// 0x0010 (0x0010 - 0x0000)
struct FModioImageWrapper final
{
public:
	class FString                                 ImagePath;                                         // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioImageWrapper;

// ScriptStruct Modio.ModioUserList
// 0x0028 (0x0028 - 0x0000)
struct FModioUserList final
{
public:
	struct FModioPagedResult                      PagedResult;                                       // 0x0000(0x0014)(BlueprintVisible, BlueprintReadOnly, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FModioUser>                     InternalList;                                      // 0x0018(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioUserList;

// ScriptStruct Modio.ModioModTagOptions
// 0x0028 (0x0028 - 0x0000)
struct FModioModTagOptions final
{
public:
	struct FModioPagedResult                      PagedResult;                                       // 0x0000(0x0014)(NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FModioModTagInfo>               InternalList;                                      // 0x0018(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioModTagOptions;

// ScriptStruct Modio.ModioTokenPack
// 0x0118 (0x0118 - 0x0000)
struct alignas(0x08) FModioTokenPack final
{
public:
	uint8                                         Pad_0[0x118];                                      // 0x0000(0x0118)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioTokenPack;

// ScriptStruct Modio.ModioTokenPackList
// 0x0028 (0x0028 - 0x0000)
struct FModioTokenPackList final
{
public:
	struct FModioPagedResult                      PagedResult;                                       // 0x0000(0x0014)(NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FModioTokenPack>                InternalList;                                      // 0x0018(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioTokenPackList;

// ScriptStruct Modio.ModioErrorCode
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FModioErrorCode final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioErrorCode;

// ScriptStruct Modio.ModioOptionalGameInfo
// 0x0238 (0x0238 - 0x0000)
struct alignas(0x08) FModioOptionalGameInfo final
{
public:
	uint8                                         Pad_0[0x238];                                      // 0x0000(0x0238)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalGameInfo;

// ScriptStruct Modio.ModioOptionalImage
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FModioOptionalImage final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalImage;

// ScriptStruct Modio.ModioOptionalModDependencyList
// 0x0040 (0x0040 - 0x0000)
struct alignas(0x08) FModioOptionalModDependencyList final
{
public:
	uint8                                         Pad_0[0x40];                                       // 0x0000(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalModDependencyList;

// ScriptStruct Modio.ModioAuthenticationParams
// 0x0078 (0x0078 - 0x0000)
struct FModioAuthenticationParams final
{
public:
	class FString                                 AuthToken;                                         // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 UserEmail;                                         // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUserHasAcceptedTerms;                             // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FString, class FString>            ExtendedParameters;                                // 0x0028(0x0050)(Edit, BlueprintVisible, DisableEditOnTemplate, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioAuthenticationParams;

// ScriptStruct Modio.ModioOptionalModInfo
// 0x01F0 (0x01F0 - 0x0000)
struct alignas(0x08) FModioOptionalModInfo final
{
public:
	uint8                                         Pad_0[0x1F0];                                      // 0x0000(0x01F0)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalModInfo;

// ScriptStruct Modio.ModioOptionalModTagOptions
// 0x0030 (0x0030 - 0x0000)
struct alignas(0x08) FModioOptionalModTagOptions final
{
public:
	uint8                                         Pad_0[0x30];                                       // 0x0000(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalModTagOptions;

// ScriptStruct Modio.ModioEmailAddress
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FModioEmailAddress final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioEmailAddress;

// ScriptStruct Modio.ModioOptionalTerms
// 0x00D8 (0x00D8 - 0x0000)
struct alignas(0x08) FModioOptionalTerms final
{
public:
	uint8                                         Pad_0[0xD8];                                       // 0x0000(0x00D8)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalTerms;

// ScriptStruct Modio.ModioMetricsSessionParams
// 0x0028 (0x0028 - 0x0000)
struct FModioMetricsSessionParams final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FModioModID>                    ModIds;                                            // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioMetricsSessionParams;

// ScriptStruct Modio.ModioOptionalUInt64
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FModioOptionalUInt64 final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalUInt64;

// ScriptStruct Modio.ModioCreateModFileParams
// 0x0078 (0x0078 - 0x0000)
struct FModioCreateModFileParams final
{
public:
	class FString                                 PathToModRootDirectory;                            // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_10[0x68];                                      // 0x0010(0x0068)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioCreateModFileParams;

// ScriptStruct Modio.ModioOptionalModInfoList
// 0x0030 (0x0030 - 0x0000)
struct alignas(0x08) FModioOptionalModInfoList final
{
public:
	uint8                                         Pad_0[0x30];                                       // 0x0000(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalModInfoList;

// ScriptStruct Modio.ModioOptionalGameInfoList
// 0x0030 (0x0030 - 0x0000)
struct alignas(0x08) FModioOptionalGameInfoList final
{
public:
	uint8                                         Pad_0[0x30];                                       // 0x0000(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalGameInfoList;

// ScriptStruct Modio.ModioModManagementEvent
// 0x0018 (0x0018 - 0x0000)
struct FModioModManagementEvent final
{
public:
	struct FModioModID                            ID;                                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EModioModManagementEventType                  Event;                                             // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FModioErrorCode                        Status;                                            // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioModManagementEvent;

// ScriptStruct Modio.ModioOptionalTransactionRecord
// 0x0020 (0x0020 - 0x0000)
struct alignas(0x08) FModioOptionalTransactionRecord final
{
public:
	uint8                                         Pad_0[0x20];                                       // 0x0000(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalTransactionRecord;

// ScriptStruct Modio.ModioEmailAuthCode
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FModioEmailAuthCode final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioEmailAuthCode;

// ScriptStruct Modio.ModioEntitlementParams
// 0x0050 (0x0050 - 0x0000)
struct FModioEntitlementParams final
{
public:
	TMap<class FString, class FString>            ExtendedParameters;                                // 0x0000(0x0050)(Edit, NativeAccessSpecifierPrivate)
};
DUMPER7_ASSERTS_FModioEntitlementParams;

// ScriptStruct Modio.ModioTokenPackID
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FModioTokenPackID final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioTokenPackID;

// ScriptStruct Modio.ModioCreateModParams
// 0x00C8 (0x00C8 - 0x0000)
struct FModioCreateModParams final
{
public:
	class FString                                 PathToLogoFile;                                    // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Name;                                              // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Summary;                                           // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_30[0x98];                                      // 0x0030(0x0098)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioCreateModParams;

// ScriptStruct Modio.ModioEditModParams
// 0x00D0 (0x00D0 - 0x0000)
struct alignas(0x08) FModioEditModParams final
{
public:
	uint8                                         Pad_0[0xD0];                                       // 0x0000(0x00D0)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioEditModParams;

// ScriptStruct Modio.ModioInitializeOptions
// 0x0090 (0x0090 - 0x0000)
struct FModioInitializeOptions final
{
public:
	struct FModioGameID                           GameId;                                            // 0x0000(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FModioApiKey                           ApiKey;                                            // 0x0008(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	EModioEnvironment                             GameEnvironment;                                   // 0x0018(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EModioPortal                                  PortalInUse;                                       // 0x0019(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A[0x6];                                       // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FString, class FString>            ExtendedInitializationParameters;                  // 0x0020(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	bool                                          bUseBackgroundThread;                              // 0x0070(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_71[0x1F];                                      // 0x0071(0x001F)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioInitializeOptions;

// ScriptStruct Modio.ModioModChangeMap
// 0x0050 (0x0050 - 0x0000)
struct FModioModChangeMap final
{
public:
	TMap<struct FModioModID, EModioModChangeType> Changes;                                           // 0x0000(0x0050)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioModChangeMap;

// ScriptStruct Modio.ModioModCollectionEntry
// 0x0220 (0x0220 - 0x0000)
struct alignas(0x08) FModioModCollectionEntry final
{
public:
	uint8                                         Pad_0[0x220];                                      // 0x0000(0x0220)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioModCollectionEntry;

// ScriptStruct Modio.ModioModCreationHandle
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FModioModCreationHandle final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioModCreationHandle;

// ScriptStruct Modio.ModioModDependency
// 0x00F8 (0x00F8 - 0x0000)
struct FModioModDependency final
{
public:
	struct FModioModID                            ModId;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ModName;                                           // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              DateAdded;                                         // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              DateUpdated;                                       // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         DependencyDepth;                                   // 0x0028(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FModioLogo                             Logo;                                              // 0x0030(0x0050)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FModioFileMetadata                     FileInfo;                                          // 0x0080(0x0070)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	EModioModServerSideStatus                     Status;                                            // 0x00F0(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EModioObjectVisibilityFlags                   Visibility;                                        // 0x00F1(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F2[0x6];                                       // 0x00F2(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioModDependency;

// ScriptStruct Modio.ModioModDependencyList
// 0x0038 (0x0038 - 0x0000)
struct FModioModDependencyList final
{
public:
	struct FModioPagedResult                      PagedResult;                                       // 0x0000(0x0014)(BlueprintVisible, BlueprintReadOnly, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FModioModDependency>            InternalList;                                      // 0x0018(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	int64                                         TotalFilesize;                                     // 0x0028(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         TotalFilesizeUncompressed;                         // 0x0030(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioModDependencyList;

// ScriptStruct Modio.ModioModProgressInfo
// 0x0050 (0x0050 - 0x0000)
struct FModioModProgressInfo final
{
public:
	struct FModioModID                            ID;                                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8[0x48];                                       // 0x0008(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioModProgressInfo;

// ScriptStruct Modio.ModioOptionalModProgressInfo
// 0x0058 (0x0058 - 0x0000)
struct alignas(0x08) FModioOptionalModProgressInfo final
{
public:
	uint8                                         Pad_0[0x58];                                       // 0x0000(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalModProgressInfo;

// ScriptStruct Modio.ModioReportParams
// 0x0058 (0x0058 - 0x0000)
struct alignas(0x08) FModioReportParams final
{
public:
	uint8                                         Pad_0[0x58];                                       // 0x0000(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioReportParams;

// ScriptStruct Modio.ModioLink
// 0x0028 (0x0028 - 0x0000)
struct FModioLink final
{
public:
	class FString                                 Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 URL;                                               // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRequired;                                         // 0x0020(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioLink;

// ScriptStruct Modio.ModioTerms
// 0x00D0 (0x00D0 - 0x0000)
struct FModioTerms final
{
public:
	class FString                                 AgreeButtonText;                                   // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DisagreeButtonText;                                // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FModioLink                             WebsiteLink;                                       // 0x0020(0x0028)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FModioLink                             TermsLink;                                         // 0x0048(0x0028)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FModioLink                             PrivacyLink;                                       // 0x0070(0x0028)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FModioLink                             ManageLink;                                        // 0x0098(0x0028)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	class FString                                 TermsText;                                         // 0x00C0(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioTerms;

// ScriptStruct Modio.ModioOptionalTokenPack
// 0x0120 (0x0120 - 0x0000)
struct alignas(0x08) FModioOptionalTokenPack final
{
public:
	uint8                                         Pad_0[0x120];                                      // 0x0000(0x0120)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalTokenPack;

// ScriptStruct Modio.ModioOptionalTokenPackList
// 0x0030 (0x0030 - 0x0000)
struct alignas(0x08) FModioOptionalTokenPackList final
{
public:
	uint8                                         Pad_0[0x30];                                       // 0x0000(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalTokenPackList;

// ScriptStruct Modio.ModioTransactionRecord
// 0x0018 (0x0018 - 0x0000)
struct FModioTransactionRecord final
{
public:
	struct FModioModID                            AssociatedModID;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FModioUnsigned64                       Price;                                             // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, NativeAccessSpecifierPublic)
	struct FModioUnsigned64                       UpdatedUserWalletBalance;                          // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioTransactionRecord;

// ScriptStruct Modio.ModioOptionalUser
// 0x0048 (0x0048 - 0x0000)
struct alignas(0x08) FModioOptionalUser final
{
public:
	uint8                                         Pad_0[0x48];                                       // 0x0000(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FModioOptionalUser;

// ScriptStruct Modio.ModioValidationError
// 0x0020 (0x0020 - 0x0000)
struct FModioValidationError final
{
public:
	class FString                                 FieldName;                                         // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ValidationFailureDescription;                      // 0x0010(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FModioValidationError;

}

