#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MPL_Camera_Shake_Draw2

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MPL_Camera_Shake_Draw2.MPL_Camera_Shake_Draw2_C
// 0x0000 (0x01F0 - 0x01F0)
class UMPL_Camera_Shake_Draw2_C final : public ULegacyCameraShake
{
public:
	void NewFunction_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MPL_Camera_Shake_Draw2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MPL_Camera_Shake_Draw2_C")
	}
	static class UMPL_Camera_Shake_Draw2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMPL_Camera_Shake_Draw2_C>();
	}
};
DUMPER7_ASSERTS_UMPL_Camera_Shake_Draw2_C;

}

