#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PPR_IsOwningPlayerDead

#include "Basic.hpp"

#include "PPR_IsOwningPlayerDead_classes.hpp"
#include "PPR_IsOwningPlayerDead_parameters.hpp"


namespace SDK
{

// Function PPR_IsOwningPlayerDead.PPR_IsOwningPlayerDead_C.EnablePostProcessEffect
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UPPR_IsOwningPlayerDead_C::EnablePostProcessEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PPR_IsOwningPlayerDead_C", "EnablePostProcessEffect");

	Params::PPR_IsOwningPlayerDead_C_EnablePostProcessEffect Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

