#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Primary_G36C

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Primary_G36C.Primary_G36C_C
// 0x0000 (0x18B0 - 0x18B0)
class APrimary_G36C_C final : public ABaseMagazineWeapon
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Primary_G36C_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Primary_G36C_C")
	}
	static class APrimary_G36C_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APrimary_G36C_C>();
	}
};
DUMPER7_ASSERTS_APrimary_G36C_C;

}

