#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Secondary_Flaregun

#include "Basic.hpp"


namespace SDK::Params
{

// Function Secondary_Flaregun.Secondary_Flaregun_C.ExecuteUbergraph_Secondary_Flaregun
// 0x0004 (0x0004 - 0x0000)
struct Secondary_Flaregun_C_ExecuteUbergraph_Secondary_Flaregun final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Secondary_Flaregun_C_ExecuteUbergraph_Secondary_Flaregun;

}

