#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SimpleButtonNormalTextStyle

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SimpleButtonNormalTextStyle.SimpleButtonNormalTextStyle_C
// 0x0000 (0x01B0 - 0x01B0)
class USimpleButtonNormalTextStyle_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SimpleButtonNormalTextStyle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SimpleButtonNormalTextStyle_C")
	}
	static class USimpleButtonNormalTextStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USimpleButtonNormalTextStyle_C>();
	}
};
DUMPER7_ASSERTS_USimpleButtonNormalTextStyle_C;

}

