#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SuspectExplosiveVest

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SuspectExplosiveVest.SuspectExplosiveVest_C
// 0x0000 (0x0E40 - 0x0E40)
class ASuspectExplosiveVest_C final : public AExplosiveVest
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SuspectExplosiveVest_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SuspectExplosiveVest_C")
	}
	static class ASuspectExplosiveVest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASuspectExplosiveVest_C>();
	}
};
DUMPER7_ASSERTS_ASuspectExplosiveVest_C;

}

