#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_BindConflictModal

#include "Basic.hpp"


namespace SDK::Params
{

// Function W_BindConflictModal.W_BindConflictModal_C.ExecuteUbergraph_W_BindConflictModal
// 0x0004 (0x0004 - 0x0000)
struct W_BindConflictModal_C_ExecuteUbergraph_W_BindConflictModal final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_BindConflictModal_C_ExecuteUbergraph_W_BindConflictModal;

}

