#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Briefing_TimelineEvents

#include "Basic.hpp"

#include "W_Briefing_TimelineEvents_classes.hpp"
#include "W_Briefing_TimelineEvents_parameters.hpp"


namespace SDK
{

// Function W_Briefing_TimelineEvents.W_Briefing_TimelineEvents_C.AddEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  EventID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Briefing_TimelineEvents_C::AddEvent(double EventID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Briefing_TimelineEvents_C", "AddEvent");

	Params::W_Briefing_TimelineEvents_C_AddEvent Parms{};

	Parms.EventID = EventID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Briefing_TimelineEvents.W_Briefing_TimelineEvents_C.EventClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  EventAudioStart                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  EventAudioDuration                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Briefing_TimelineEvents_C::EventClicked(double EventAudioStart, double EventAudioDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Briefing_TimelineEvents_C", "EventClicked");

	Params::W_Briefing_TimelineEvents_C_EventClicked Parms{};

	Parms.EventAudioStart = EventAudioStart;
	Parms.EventAudioDuration = EventAudioDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Briefing_TimelineEvents.W_Briefing_TimelineEvents_C.ExecuteUbergraph_W_Briefing_TimelineEvents
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Briefing_TimelineEvents_C::ExecuteUbergraph_W_Briefing_TimelineEvents(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Briefing_TimelineEvents_C", "ExecuteUbergraph_W_Briefing_TimelineEvents");

	Params::W_Briefing_TimelineEvents_C_ExecuteUbergraph_W_Briefing_TimelineEvents Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Briefing_TimelineEvents.W_Briefing_TimelineEvents_C.Finished_CEF1E049428EE21AB58B96A8441038EA
// (BlueprintCallable, BlueprintEvent)

void UW_Briefing_TimelineEvents_C::Finished_CEF1E049428EE21AB58B96A8441038EA()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Briefing_TimelineEvents_C", "Finished_CEF1E049428EE21AB58B96A8441038EA");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Briefing_TimelineEvents.W_Briefing_TimelineEvents_C.Initialize
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const TMap<double, struct FTimelineEvent>&EventEntries_0                                         (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_Briefing_TimelineEvents_C::Initialize(const TMap<double, struct FTimelineEvent>& EventEntries_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Briefing_TimelineEvents_C", "Initialize");

	Params::W_Briefing_TimelineEvents_C_Initialize Parms{};

	Parms.EventEntries_0 = std::move(EventEntries_0);

	UObject::ProcessEvent(Func, &Parms);
}

}

