#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_FireModeChanged

#include "Basic.hpp"

#include "W_FireModeChanged_classes.hpp"
#include "W_FireModeChanged_parameters.hpp"


namespace SDK
{

// Function W_FireModeChanged.W_FireModeChanged_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_FireModeChanged_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FireModeChanged_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_FireModeChanged.W_FireModeChanged_C.ExecuteUbergraph_W_FireModeChanged
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FireModeChanged_C::ExecuteUbergraph_W_FireModeChanged(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FireModeChanged_C", "ExecuteUbergraph_W_FireModeChanged");

	Params::W_FireModeChanged_C_ExecuteUbergraph_W_FireModeChanged Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

