#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_IllegalUnbindModal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_IllegalUnbindModal.W_IllegalUnbindModal_C
// 0x0008 (0x04C8 - 0x04C0)
class UW_IllegalUnbindModal_C final : public UIllegalUnbindModal
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void Construct();
	void ExecuteUbergraph_W_IllegalUnbindModal(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_IllegalUnbindModal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_IllegalUnbindModal_C")
	}
	static class UW_IllegalUnbindModal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_IllegalUnbindModal_C>();
	}
};
DUMPER7_ASSERTS_UW_IllegalUnbindModal_C;

}

