#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ItemSelectionMenu_V2

#include "Basic.hpp"

#include "W_ItemSelectionMenu_V2_classes.hpp"
#include "W_ItemSelectionMenu_V2_parameters.hpp"


namespace SDK
{

// Function W_ItemSelectionMenu_V2.W_ItemSelectionMenu_V2_C.CloseMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UW_ItemSelectionMenu_V2_C::CloseMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemSelectionMenu_V2_C", "CloseMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_ItemSelectionMenu_V2.W_ItemSelectionMenu_V2_C.ConfirmSelection
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ItemSelectionMenu_V2_C::ConfirmSelection(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemSelectionMenu_V2_C", "ConfirmSelection");

	Params::W_ItemSelectionMenu_V2_C_ConfirmSelection Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ItemSelectionMenu_V2.W_ItemSelectionMenu_V2_C.ExecuteUbergraph_W_ItemSelectionMenu_V2
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ItemSelectionMenu_V2_C::ExecuteUbergraph_W_ItemSelectionMenu_V2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemSelectionMenu_V2_C", "ExecuteUbergraph_W_ItemSelectionMenu_V2");

	Params::W_ItemSelectionMenu_V2_C_ExecuteUbergraph_W_ItemSelectionMenu_V2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ItemSelectionMenu_V2.W_ItemSelectionMenu_V2_C.Get Item Categories
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AReadyOrNotCharacter*             self2                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<struct FItemSelectionGroup>*     ItemSelectionGroups                                    (Parm, OutParm)

void UW_ItemSelectionMenu_V2_C::Get_Item_Categories(class AReadyOrNotCharacter* self2, TArray<struct FItemSelectionGroup>* ItemSelectionGroups)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemSelectionMenu_V2_C", "Get Item Categories");

	Params::W_ItemSelectionMenu_V2_C_Get_Item_Categories Parms{};

	Parms.self2 = self2;

	UObject::ProcessEvent(Func, &Parms);

	if (ItemSelectionGroups != nullptr)
		*ItemSelectionGroups = std::move(Parms.ItemSelectionGroups);
}


// Function W_ItemSelectionMenu_V2.W_ItemSelectionMenu_V2_C.Initialize
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bForce                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const TArray<struct FItemSelectionGroup>&InItemSelectionGroups                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_ItemSelectionMenu_V2_C::Initialize(bool bForce, const TArray<struct FItemSelectionGroup>& InItemSelectionGroups)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemSelectionMenu_V2_C", "Initialize");

	Params::W_ItemSelectionMenu_V2_C_Initialize Parms{};

	Parms.bForce = bForce;
	Parms.InItemSelectionGroups = std::move(InItemSelectionGroups);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ItemSelectionMenu_V2.W_ItemSelectionMenu_V2_C.OpenMenu
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ItemSelectionMenu_V2_C::OpenMenu(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemSelectionMenu_V2_C", "OpenMenu");

	Params::W_ItemSelectionMenu_V2_C_OpenMenu Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ItemSelectionMenu_V2.W_ItemSelectionMenu_V2_C.SelectCategory
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ItemSelectionMenu_V2_C::SelectCategory(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemSelectionMenu_V2_C", "SelectCategory");

	Params::W_ItemSelectionMenu_V2_C_SelectCategory Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ItemSelectionMenu_V2.W_ItemSelectionMenu_V2_C.Update Menu
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FItemSelectionGroup>&     InItemGroups                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_ItemSelectionMenu_V2_C::Update_Menu(TArray<struct FItemSelectionGroup>& InItemGroups)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemSelectionMenu_V2_C", "Update Menu");

	Params::W_ItemSelectionMenu_V2_C_Update_Menu Parms{};

	Parms.InItemGroups = std::move(InItemGroups);

	UObject::ProcessEvent(Func, &Parms);

	InItemGroups = std::move(Parms.InItemGroups);
}

}

