#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PreMission_Tablet_Brief_SubjectListItem

#include "Basic.hpp"

#include "W_PreMission_Tablet_Brief_SubjectListItem_classes.hpp"
#include "W_PreMission_Tablet_Brief_SubjectListItem_parameters.hpp"


namespace SDK
{

// Function W_PreMission_Tablet_Brief_SubjectListItem.W_PreMission_Tablet_Brief_SubjectListItem_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_PreMission_Tablet_Brief_SubjectListItem_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PreMission_Tablet_Brief_SubjectListItem_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_PreMission_Tablet_Brief_SubjectListItem.W_PreMission_Tablet_Brief_SubjectListItem_C.ExecuteUbergraph_W_PreMission_Tablet_Brief_SubjectListItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_PreMission_Tablet_Brief_SubjectListItem_C::ExecuteUbergraph_W_PreMission_Tablet_Brief_SubjectListItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PreMission_Tablet_Brief_SubjectListItem_C", "ExecuteUbergraph_W_PreMission_Tablet_Brief_SubjectListItem");

	Params::W_PreMission_Tablet_Brief_SubjectListItem_C_ExecuteUbergraph_W_PreMission_Tablet_Brief_SubjectListItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

