#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ServerBrowser

#include "Basic.hpp"

#include "W_ServerBrowser_classes.hpp"
#include "W_ServerBrowser_parameters.hpp"


namespace SDK
{

// Function W_ServerBrowser.W_ServerBrowser_C.BndEvt__W_ServerBrowser_btn_Difficulty_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::BndEvt__W_ServerBrowser_btn_Difficulty_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "BndEvt__W_ServerBrowser_btn_Difficulty_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature");

	Params::W_ServerBrowser_C_BndEvt__W_ServerBrowser_btn_Difficulty_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.BndEvt__W_ServerBrowser_btn_HostName_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::BndEvt__W_ServerBrowser_btn_HostName_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "BndEvt__W_ServerBrowser_btn_HostName_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature");

	Params::W_ServerBrowser_C_BndEvt__W_ServerBrowser_btn_HostName_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.BndEvt__W_ServerBrowser_btn_MissionBrief_K2Node_ComponentBoundEvent_2_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::BndEvt__W_ServerBrowser_btn_MissionBrief_K2Node_ComponentBoundEvent_2_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "BndEvt__W_ServerBrowser_btn_MissionBrief_K2Node_ComponentBoundEvent_2_Clicked__DelegateSignature");

	Params::W_ServerBrowser_C_BndEvt__W_ServerBrowser_btn_MissionBrief_K2Node_ComponentBoundEvent_2_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.BndEvt__W_ServerBrowser_btn_Next_K2Node_ComponentBoundEvent_17_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::BndEvt__W_ServerBrowser_btn_Next_K2Node_ComponentBoundEvent_17_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "BndEvt__W_ServerBrowser_btn_Next_K2Node_ComponentBoundEvent_17_Clicked__DelegateSignature");

	Params::W_ServerBrowser_C_BndEvt__W_ServerBrowser_btn_Next_K2Node_ComponentBoundEvent_17_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.BndEvt__W_ServerBrowser_btn_Ping_K2Node_ComponentBoundEvent_6_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::BndEvt__W_ServerBrowser_btn_Ping_K2Node_ComponentBoundEvent_6_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "BndEvt__W_ServerBrowser_btn_Ping_K2Node_ComponentBoundEvent_6_Clicked__DelegateSignature");

	Params::W_ServerBrowser_C_BndEvt__W_ServerBrowser_btn_Ping_K2Node_ComponentBoundEvent_6_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.BndEvt__W_ServerBrowser_btn_Players_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::BndEvt__W_ServerBrowser_btn_Players_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "BndEvt__W_ServerBrowser_btn_Players_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature");

	Params::W_ServerBrowser_C_BndEvt__W_ServerBrowser_btn_Players_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.BndEvt__W_ServerBrowser_btn_Prev_K2Node_ComponentBoundEvent_16_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::BndEvt__W_ServerBrowser_btn_Prev_K2Node_ComponentBoundEvent_16_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "BndEvt__W_ServerBrowser_btn_Prev_K2Node_ComponentBoundEvent_16_Clicked__DelegateSignature");

	Params::W_ServerBrowser_C_BndEvt__W_ServerBrowser_btn_Prev_K2Node_ComponentBoundEvent_16_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.BndEvt__W_ServerBrowser_FriendsServerListView_K2Node_ComponentBoundEvent_0_OnItemIsHoveredChangedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsHovered                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::BndEvt__W_ServerBrowser_FriendsServerListView_K2Node_ComponentBoundEvent_0_OnItemIsHoveredChangedDynamic__DelegateSignature(class UObject* Item, bool bIsHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "BndEvt__W_ServerBrowser_FriendsServerListView_K2Node_ComponentBoundEvent_0_OnItemIsHoveredChangedDynamic__DelegateSignature");

	Params::W_ServerBrowser_C_BndEvt__W_ServerBrowser_FriendsServerListView_K2Node_ComponentBoundEvent_0_OnItemIsHoveredChangedDynamic__DelegateSignature Parms{};

	Parms.Item = Item;
	Parms.bIsHovered = bIsHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.BndEvt__W_ServerBrowser_GlobalServerListView_K2Node_ComponentBoundEvent_7_OnItemIsHoveredChangedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsHovered                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::BndEvt__W_ServerBrowser_GlobalServerListView_K2Node_ComponentBoundEvent_7_OnItemIsHoveredChangedDynamic__DelegateSignature(class UObject* Item, bool bIsHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "BndEvt__W_ServerBrowser_GlobalServerListView_K2Node_ComponentBoundEvent_7_OnItemIsHoveredChangedDynamic__DelegateSignature");

	Params::W_ServerBrowser_C_BndEvt__W_ServerBrowser_GlobalServerListView_K2Node_ComponentBoundEvent_7_OnItemIsHoveredChangedDynamic__DelegateSignature Parms{};

	Parms.Item = Item;
	Parms.bIsHovered = bIsHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.BndEvt__W_ServerBrowser_PageWrapper_K2Node_ComponentBoundEvent_10_OnNavOptionSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FName                             OptionNameID                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::BndEvt__W_ServerBrowser_PageWrapper_K2Node_ComponentBoundEvent_10_OnNavOptionSelected__DelegateSignature(class FName OptionNameID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "BndEvt__W_ServerBrowser_PageWrapper_K2Node_ComponentBoundEvent_10_OnNavOptionSelected__DelegateSignature");

	Params::W_ServerBrowser_C_BndEvt__W_ServerBrowser_PageWrapper_K2Node_ComponentBoundEvent_10_OnNavOptionSelected__DelegateSignature Parms{};

	Parms.OptionNameID = OptionNameID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.BndEvt__W_ServerBrowser_PageWrapper_K2Node_ComponentBoundEvent_1_OnFooterButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    ButtonId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::BndEvt__W_ServerBrowser_PageWrapper_K2Node_ComponentBoundEvent_1_OnFooterButtonClicked__DelegateSignature(const class FString& ButtonId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "BndEvt__W_ServerBrowser_PageWrapper_K2Node_ComponentBoundEvent_1_OnFooterButtonClicked__DelegateSignature");

	Params::W_ServerBrowser_C_BndEvt__W_ServerBrowser_PageWrapper_K2Node_ComponentBoundEvent_1_OnFooterButtonClicked__DelegateSignature Parms{};

	Parms.ButtonId = std::move(ButtonId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_ServerBrowser_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_ServerBrowser.W_ServerBrowser_C.DeselectButtons
// (Public, BlueprintCallable, BlueprintEvent)

void UW_ServerBrowser_C::DeselectButtons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "DeselectButtons");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_ServerBrowser.W_ServerBrowser_C.ExecuteUbergraph_W_ServerBrowser
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::ExecuteUbergraph_W_ServerBrowser(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "ExecuteUbergraph_W_ServerBrowser");

	Params::W_ServerBrowser_C_ExecuteUbergraph_W_ServerBrowser Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.Set Host Name
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UServerListData*                  Server_Item_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::Set_Host_Name(class UServerListData* Server_Item_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "Set Host Name");

	Params::W_ServerBrowser_C_Set_Host_Name Parms{};

	Parms.Server_Item_0 = Server_Item_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.Set Latency
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UServerListData*                  Server_Item_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::Set_Latency(class UServerListData* Server_Item_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "Set Latency");

	Params::W_ServerBrowser_C_Set_Latency Parms{};

	Parms.Server_Item_0 = Server_Item_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.Set Player Count
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UServerListData*                  Server_Item_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::Set_Player_Count(class UServerListData* Server_Item_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "Set Player Count");

	Params::W_ServerBrowser_C_Set_Player_Count Parms{};

	Parms.Server_Item_0 = Server_Item_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerBrowser.W_ServerBrowser_C.SetSelectedState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ID                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Deselect                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ServerBrowser_C::SetSelectedState(int32 ID, bool Deselect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerBrowser_C", "SetSelectedState");

	Params::W_ServerBrowser_C_SetSelectedState Parms{};

	Parms.ID = ID;
	Parms.Deselect = Deselect;

	UObject::ProcessEvent(Func, &Parms);
}

}

