#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_StandardCheckbox

#include "Basic.hpp"

#include "W_StandardCheckbox_classes.hpp"
#include "W_StandardCheckbox_parameters.hpp"


namespace SDK
{

// Function W_StandardCheckbox.W_StandardCheckbox_C.BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UW_StandardCheckbox_C::BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_StandardCheckbox_C", "BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_StandardCheckbox.W_StandardCheckbox_C.BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UW_StandardCheckbox_C::BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_StandardCheckbox_C", "BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_StandardCheckbox.W_StandardCheckbox_C.BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature
// (BlueprintEvent)

void UW_StandardCheckbox_C::BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_StandardCheckbox_C", "BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_StandardCheckbox.W_StandardCheckbox_C.BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_StandardCheckbox_C::BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_StandardCheckbox_C", "BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_StandardCheckbox.W_StandardCheckbox_C.BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_StandardCheckbox_C::BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_StandardCheckbox_C", "BndEvt__CheckboxButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_StandardCheckbox.W_StandardCheckbox_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_StandardCheckbox_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_StandardCheckbox_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_StandardCheckbox.W_StandardCheckbox_C.ExecuteUbergraph_W_StandardCheckbox
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_StandardCheckbox_C::ExecuteUbergraph_W_StandardCheckbox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_StandardCheckbox_C", "ExecuteUbergraph_W_StandardCheckbox");

	Params::W_StandardCheckbox_C_ExecuteUbergraph_W_StandardCheckbox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_StandardCheckbox.W_StandardCheckbox_C.OnSynchronizeProperties
// (Event, Public, BlueprintEvent)

void UW_StandardCheckbox_C::OnSynchronizeProperties()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_StandardCheckbox_C", "OnSynchronizeProperties");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_StandardCheckbox.W_StandardCheckbox_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_StandardCheckbox_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_StandardCheckbox_C", "PreConstruct");

	Params::W_StandardCheckbox_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_StandardCheckbox.W_StandardCheckbox_C.SetCheckedState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_StandardCheckbox_C::SetCheckedState(bool NewChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_StandardCheckbox_C", "SetCheckedState");

	Params::W_StandardCheckbox_C_SetCheckedState Parms{};

	Parms.NewChecked = NewChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_StandardCheckbox.W_StandardCheckbox_C.UpdateCheckVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UW_StandardCheckbox_C::UpdateCheckVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_StandardCheckbox_C", "UpdateCheckVisibility");

	UObject::ProcessEvent(Func, nullptr);
}

}

