#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SubObjective_Entry

#include "Basic.hpp"

#include "W_SubObjective_Entry_classes.hpp"
#include "W_SubObjective_Entry_parameters.hpp"


namespace SDK
{

// Function W_SubObjective_Entry.W_SubObjective_Entry_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_SubObjective_Entry_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SubObjective_Entry_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SubObjective_Entry.W_SubObjective_Entry_C.ExecuteUbergraph_W_SubObjective_Entry
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SubObjective_Entry_C::ExecuteUbergraph_W_SubObjective_Entry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SubObjective_Entry_C", "ExecuteUbergraph_W_SubObjective_Entry");

	Params::W_SubObjective_Entry_C_ExecuteUbergraph_W_SubObjective_Entry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_SubObjective_Entry.W_SubObjective_Entry_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SubObjective_Entry_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SubObjective_Entry_C", "PreConstruct");

	Params::W_SubObjective_Entry_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_SubObjective_Entry.W_SubObjective_Entry_C.SetState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_SubObjective_Entry_C::SetState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SubObjective_Entry_C", "SetState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SubObjective_Entry.W_SubObjective_Entry_C.Update
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Complete_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Failed_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      ObjectiveDescription_0                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_SubObjective_Entry_C::Update(bool Complete_0, bool Failed_0, const class FText& ObjectiveDescription_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SubObjective_Entry_C", "Update");

	Params::W_SubObjective_Entry_C_Update Parms{};

	Parms.Complete_0 = Complete_0;
	Parms.Failed_0 = Failed_0;
	Parms.ObjectiveDescription_0 = std::move(ObjectiveDescription_0);

	UObject::ProcessEvent(Func, &Parms);
}

}

